name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.x'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test
        run: go test -v ./tests/...

  changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_release:
    needs: [test, changelog]
    runs-on: ubuntu-latest
    steps:
      - name: Create Draft Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body: ${{ needs.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_upload:
    needs: [create_release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows, linux]
        arch: [amd64, arm64, 386]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Build
        run: |
          output_dir="dist"
          mkdir -p "$output_dir"
          version_tag=${GITHUB_REF#refs/tags/}
          output_name="postfix-to-cloudflare-${{ matrix.platform }}-${{ matrix.arch }}-${version_tag}"
          if [ "${{ matrix.arch }}" == "arm64" ] && [ "${{ matrix.platform }}" == "linux" ]; then
            GOARM="7"
            output_name+="-v7"
          fi
          if [ "${{ matrix.platform }}" == "windows" ]; then
            output_name+=".exe"
          fi
          env CGO_ENABLED=0 GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} GOARM=$GOARM go build -o "$output_dir/$output_name" ./main

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
          body: ${{ needs.changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
