name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.x'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Test
      run: go test -v ./tests/...
